# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20170407_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='docfile',
            new_name='banner',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('html', 'html'), ('css', 'css'), ('js', 'javascript'), ('all', 'AMAZING')], default='html', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
