# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0008_auto_20170407_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='listCodeScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('html_file_path', models.FileField(upload_to='codescript')),
                ('css_file_path', models.FileField(upload_to='codescript')),
                ('js_file_path', models.FileField(upload_to='codescript')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stars', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('html', 'html'), ('css', 'css'), ('js', 'javascript'), ('all', 'Other')], max_length=20),
        ),
    ]
