# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20170421_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcodescript',
            name='stars',
        ),
        migrations.AddField(
            model_name='listcodescript',
            name='banner',
            field=models.FileField(default=django.utils.timezone.now, upload_to='codescript/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
