# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import poll.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20170424_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='article',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=poll.models.upload_location, width_field='width_field'),
        ),
    ]
