# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_auto_20170427_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
