# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_article_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codescript',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
        migrations.DeleteModel(
            name='CodeScript',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
